package mocks

import gin "gopkg.in/gin-gonic/gin.v1"
import handlers "github.com/lcollin/warehouse/handlers"
import mock "github.com/stretchr/testify/mock"

// OrderIfc is an autogenerated mock type for the OrderIfc type
type OrderIfc struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx
func (_m *OrderIfc) Delete(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetJWT provides a mock function with given fields:
func (_m *OrderIfc) GetJWT() gin.HandlerFunc {
	ret := _m.Called()

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// GetShippingLabel provides a mock function with given fields: ctx
func (_m *OrderIfc) GetShippingLabel(ctx *gin.Context) {
	_m.Called(ctx)
}

// New provides a mock function with given fields: ctx
func (_m *OrderIfc) New(ctx *gin.Context) {
	_m.Called(ctx)
}

// Time provides a mock function with given fields:
func (_m *OrderIfc) Time() gin.HandlerFunc {
	ret := _m.Called()

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// Update provides a mock function with given fields: ctx
func (_m *OrderIfc) Update(ctx *gin.Context) {
	_m.Called(ctx)
}

// View provides a mock function with given fields: ctx
func (_m *OrderIfc) View(ctx *gin.Context) {
	_m.Called(ctx)
}

// ViewAll provides a mock function with given fields: ctx
func (_m *OrderIfc) ViewAll(ctx *gin.Context) {
	_m.Called(ctx)
}

var _ handlers.OrderIfc = (*OrderIfc)(nil)
