DROP TABLE IF EXISTS item;
CREATE TABLE item(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	roasterID VARCHAR(36) NOT NULL,
	name VARCHAR(100) NOT NULL,
	pictureURL VARCHAR(200),
	coffeeType VARCHAR(100) NOT NULL,
	inStockBags INTEGER NOT NULL,
	providerPrice DECIMAL(5,2) NOT NULL,
	consumerPrice DECIMAL(5,2) NOT NULL,
	ozInBag DECIMAL(5,2) NOT NULL
);