DROP TABLE IF EXISTS order;
CREATE TABLE order(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	userID VARCHAR(36) NOT NULL,
	subscriptionID VARCHAR(36) NOT NULL,
	requestDate TIMESTAMP NOT NULL,
	shipDate TIMESTAMP
);