DROP TABLE IF EXISTS item;
CREATE TABLE user(
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	passHash VARCHAR(50) NOT NULL,
	firstName VARCHAR(20) NOT NULL,
	lastName VARCHAR(20) NOT NULL,
	email VARCHAR(200) NOT NULL,
	phone VARCHAR(12),
	addressLine1 VARCHAR(200) NOT NULL,
	addressLine2 VARCHAR(200) NOT NULL,
	addressCity VARCHAR(30) NOT NULL,
	addressState VARCHAR(30) NOT NULL,
	addressZip VARCHAR(10) NOT NULL,
	addressCountry VARCHAR(20) NOT NULL,
	roasterId VARCHAR(36),
	isRoaster SMALLINT
);